export NVM_DIR="$HOME/.nvm"
   . "/usr/local/opt/nvm/nvm.sh"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jayantbhambhani/google-cloud-sdk/path.bash.inc' ]; then source '/Users/jayantbhambhani/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jayantbhambhani/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/jayantbhambhani/google-cloud-sdk/completion.bash.inc'; fi

# We're enabling bash completion for git too
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# because Postgres.app sucks
alias psql='/Applications/Postgres.app/Contents/Versions/latest/bin/psql'
